@host=http://localhost
@port=3000
@consultaOrigem=Avenida Lisboa, 234, Contagem, MG
@consultaDestino=Rua Carlos da Cunha Peixoto, 1080, Jequitinhonha, MG

@originId=
@destinationId=

### Consulta Origem
# @name getOrigin
GET {{host}}:{{port}}/places?text={{consultaOrigem}}

@originId = {{ getOrigin.response.body.candidates[0].place_id }}

### Consulta Destino
# @name getDestination
GET {{host}}:{{port}}/places?text={{consultaDestino}}

@destinationId = {{ getDestination.response.body.candidates[0].place_id }}

### GET /places/{originId}/routes/{destinationId}
GET {{host}}:{{port}}/directions?originId={{originId}}&destinationId={{destinationId}}

### POST /routes
POST {{host}}:{{port}}/routes
Content-Type: application/json

{
  "name": "Contagem > Jequi 1",
  "source_id": "{{ originId }}",
  "destination_id": "{{ destinationId }}"
}

### POST /routes/{:id}/start

POST {{host}}:{{port}}/routes/676dac2e227824fedb4949ad/start

### GET /routes
GET {{host}}:{{port}}/routes

### GET /routes/{id}
GET {{host}}:{{port}}/routes/6758ae1443b4ff7d3c052d22